### ISSUE TITLE
How does this extension know where model files are located?

### ISSUE THREAD

**Issue by skwon615** [innoverio/vscode-dbt-power-user#116]
Hello! When I try going to the definition of a model, VS Code tries to open a file in a directory that's different from where the model is actually located. So I'm curious where the extension looks to find the root folder for my models, and if it's possible to customize that.

Thank you!

**Comment by CampaginAgent** [comment]
Are you using devcontainers? If so, I'm having the same issue.  I keep getting the message `The editor could not be opened because the file was not found`.

My container folder is `oot@77295f50ed01:/workspaces/data-warehouse-2-dbt# `, witi the file being in /models/example/

The file that the dbt power user extension is looking for is in /dbt/models/example/

I'm not sure how to align these 2 paths.

**Comment by CR-Lough** [comment]
Hi @skwon615, did you ever end up finding out how it does so?

**Comment by skwon615** [comment]
@CR-Lough no, unfortunately not yet :(

**Comment by CR-Lough** [comment]
Hey @skwon615 I'm pretty sure this is an "us" issue. I see now that this extension was built to show parent/child/tests only for _the file currently open_. Not to show all models in the project.

Let me know if that works for you.

**Comment by skwon615** [comment]
Ah, got it...thanks, I guess that means I can't use this extension, but good to know!
