### ISSUE TITLE
Feature Request: Add ability to run dbt model and all upstream models

### ISSUE THREAD

**Issue by jaredx435k2d0** [innoverio/vscode-dbt-power-user#127]
Currently, it seems like the "Run dbt model" command only works if all upstream models are already built.

If a user didn't already have them all built, or wanted them all refreshed, it'd be great to use the [plus operator in front to also select all parent models](https://docs.getdbt.com/reference/node-selection/graph-operators#the-plus-operator).

**Comment by z3z1ma** [comment]
This already exists in the sidebar as a function exposed there in the parent + child tree views. 

Closing this for now we don't want to run all upstream models on "Run dbt model" command but instead defer it to the existing explicit command. Feel free to comment if you have more detail to add otherwise.

**Comment by jaredx435k2d0** [comment]
@z3z1ma , thanks for pointing that out! I'd totally missed that.

This is just my two cents, but the tooltip "Run Upstream Models" doesn't intuitively communicate that it'll also run the open model itself as well.
