### ISSUE TITLE
Refresh the manifest on load

### ISSUE THREAD

**Issue by bastienboutonnet** [innoverio/vscode-dbt-power-user#19]
I think there might be a good case for triggering a refresh of the manifest as you load the project (or actually generate it if it doesn't exist yet)

the `dbt ls` command generates the artifacts which should be the fastest way to get it.

One caveat I see is that if people are using dbt from a venv then we might have to find what that venv is. One solution perhaps is offer a config option where people point to the venv so that it can be activated. A bit like what the Python extension is doing for its formatters and linters.

That'd be super neat!

**Comment by mdesmet** [comment]
With the python you need to select the python interpreter and then it will trigger the venv activation on each new terminal. It seems to work already since we added the delay as the venv activation is triggered on each terminal creation asynchronously in the vscode python extension and we have to let the JS engine switch to the venv activation before we run our dbt command. Haven't tested this enough as I don't currently use a venv setup.

I think the compilation could be implemented as following:

- Detect if the packages are installed, if not offer the option to run 'dbt deps', if yes go to next step
- Detect if code is compiled, if not offer the option to run 'dbt ls'

What do you think about that?

**Comment by bastienboutonnet** [comment]
Oh yeah that makes sense that you could piggie back on the python extension, might be a good idea to make it a requirement or prompt people to install it if they don't already have it.

Regarding the steps, yep makes sense. For point 2 would you check if something has been compiled at all or would you do something a bit more involved such as "there are new models and they haven't been compiled would you like to compile? or --looks like you haven't compiled anything for a few days, wanna refresh? (the second option which is simple could get annoying so maybe we'd have to give people a chance to shut up the message.

Regarding venvs and testing, do you want me to give it a go? Is there a version on a branch somewhere that I could try out?

**Comment by bastienboutonnet** [comment]
Also, although I wouldn't be super fast, I'd be super interested in contributing to that functionality with a bit of guidance if you feel like it

**Comment by mdesmet** [comment]
Hey @bastienboutonnet ,

You could have a look at https://github.com/microsoft/vscode-extension-samples/tree/master/task-provider-sample/src

that explains how to:

- Setup a task provider
- How to execute a task when certain files have changed.
