### ISSUE TITLE
Can we make `dbt ls` to be configured not to be done automaticaly?

### ISSUE THREAD

**Issue by jesse23** [innoverio/vscode-dbt-power-user#38]
Hi,

Looks latest upgrade creates a dependency on python extension? It is causing several 'regressions' on my setup:

- my dbt installation is done by homebrew which is not using default python, without switching python context it complains `no dbt installatoin in curent python`.

- A complain on toolbar `your dbt is not up to date`. In my use case for I am still on 0.18

- Any minor change to sql file will cause a long time list model operation....the rerun cannot start before that is done. Every change-validation cycle takes around 5 mins...

- All the logs goes to `dbt output` ( I guess that is an improvement ? ), Looks cool but if I have multiple run it is hard to identify the log without syntax highlight ( which is in terminal print ). Also new terminal provides more flexibility.

**Comment by jesse23** [comment]
But in general it is a very nice plugin - I can stay focusing on my editor for project work. Thanks for the effort!

**Comment by mdesmet** [comment]
Hi Jesse,

Thanks for your remarks!

The first and second point I would rather consider features. There will be a lot of improvements coming where we need to be able to run DBT/Python code. Note that we don't require the user to update, but just mention that there is a newer version available.

The third one we just fixed a bug for. We had coded a debounce that ensures the list is not triggered multiple times if a file is changed but that was not working as expected.  Can you verify that you are on v0.4.2? If that doesn't fix the issue I would like to know how long a `dbt ls` takes.

I agree on the output for the runs, they should actually use a pseudo terminal instead of the output channel which doesn't support colors. See https://github.com/microsoft/vscode/issues/571. I gave the terminal a quick try just before the release but that gave other display issues. We can probably fix that soon.

**Comment by jesse23** [comment]
Thanks!

- I just down grade from 0.4.2 to 0.3.6 - can we provide an option to disable it or manual refresh it? 
  - Yes the `dbt ls` at my local takes 2 minutes.

**Comment by mdesmet** [comment]
dbt list should be really fast, it just looks at all your refs and regenerate the model graph. How many models are there in your project?

We can indeed make this configurable to not automatically execute dbt list on source file change.

**Comment by jesse23** [comment]
Thanks! Configurable will definitely help. Yes no doubt that my project is complex.

**Comment by mdesmet** [comment]
Hi Jesse,

I will release a new version shortly with following flag to disable the automatic listing.

![image](https://user-images.githubusercontent.com/9265503/105542450-a896cf80-5cf9-11eb-838d-40f5213ca667.png)

**Comment by jesse23** [comment]
Works fine. Also I can see the output has been in a terminal as `Tasks -dbt`. Thanks!
