### ISSUE TITLE
Extension reporting incorrect dbt version in VSCode status bar

### ISSUE THREAD

**Issue by radian21** [innoverio/vscode-dbt-power-user#69]
The extension previously reported by dbt version as current (v0.19.1 as of this writing).  However, in the past couple of days, it is now reporting "dbt 0.18.2 is not up to date".  I can confirm that my installed version is 0.19.1.  I'm not running dbt and python in a virtual environment.

![image](https://user-images.githubusercontent.com/4933973/123280135-255aef00-d4ce-11eb-8871-9257009ebb0b.png)

When I use the extension to update dbt, the process doesn't complete hanging on the `dbt --version` task.

![image](https://user-images.githubusercontent.com/4933973/123280312-4cb1bc00-d4ce-11eb-836d-ae63fb8b0fae.png)

**Comment by mdesmet** [comment]
The screenshots are not conclusive. Maybe you have different python environments installed. Also what you see there is not really hanging, actually dbt --version outputs to the error instead of standard output, so no output is displayed there (only listening on standard output).

![image](https://user-images.githubusercontent.com/9265503/123283090-56a5e000-d50b-11eb-834c-9409f6beea97.png)

**Comment by radian21** [comment]
Thanks for the python tip.  I had two python versions installed (3.8.1 and 3.8.8).  Somehow, the 3.8.1 got selected causing the extension to report the older dbt version. Switching the interpreter back to python 3.8.8 caused the extension to see dbt 0.19.1 that is installed.  Thanks again.

**Comment by mdesmet** [comment]
That's indeed how it's supposed to work. If the extension makes your life easier, please rate the extension on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

If you have any other feedback, please let us know!
