### ISSUE TITLE
Issue when the machine is behind a proxy (dbt --version called)

### ISSUE THREAD

**Issue by b-per** [innoverio/vscode-dbt-power-user#70]
I can't make the extension work when I am behind a corporate proxy blocking some websites. From what I can see, this is because of a call to `dbt --version` that goes to pypi and/or github. 
Calling `dbt --version` directly times out after 30 seconds on my computer.

For now, my workaround has been to change the call to `dbt --version` by `dbt debug` (which also returns the version currently installed) that doesn't need to send requests to the Internet.

There could potentially be an option for in the extension to activate/deactivate checking the latest version?

**Comment by mdesmet** [comment]
Hi b-per,

That's definitely a good suggestion. Indeed it seems more reasonable to split the update check and dbt verification. I will provide a fix shortly.

**Comment by mdesmet** [comment]
Hi @b-per,

I've released a version on sunday. the dbt detection is now based on being able to load the python library instead of calling the version. We still do the version check but bail out after 5s.

Let me know if it fixes the issue? 

If you like the extension please rate us at https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

**Comment by b-per** [comment]
Amazing! It works great on my computer behind a proxy. 

The only thing now is that the computer NOT behind a proxy doesn't show the version anymore, most likely due to the fact that `dbt --version` takes about 7 secs to return results. I will close this one and raise another issue about slightly increasing the timeout for dbt to check the version.

On my way to the store to rate it 5 stars!
