### ISSUE TITLE
"Missing profile" error when opening a workspace

### ISSUE THREAD

**Issue by ljhopkins2** [innoverio/vscode-dbt-power-user#98]
I've just started having an issue with the extension (v0.5.9). I recently upgraded to dbt v1.0.1 from v0.21.
```
dbt version: 1.0.1
python version: 3.7.7
python path: /Users/<me>/Documents/GitHub/data-warehouse/.venv/bin/python3
os info: Darwin-21.1.0-x86_64-i386-64bit
Using profiles.yml file at /Users/<me>/.dbt/profiles.yml
Using dbt_project.yml file at /Users/<me>/Documents/GitHub/data-warehouse/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]
```
I've confirmed the python path above is the one being used by the VS Code workspace.

When first opening a workspace with my dbt project in it, the `Tasks - dbt` terminal displays the following:
```
> Executing task:  dbt list

> Executing task:  dbt list

> Executing task:  dbt list

07:53:31  Encountered an error while reading the project:
07:53:31    ERROR: Runtime Error
  dbt cannot run because no profile was specified for this dbt project.
  To specify a profile for this project, add a line like the this to
  your dbt_project.yml file:
  
  profile: [profile name]
  
  Here, [profile name] should be replaced with a profile name
  defined in your profiles.yml file. You can find profiles.yml here:
  
  /Users/<me>/.dbt/profiles.yml
  
07:53:31  Encountered an error:
Runtime Error
  Could not run dbt
07:53:31  Encountered an error while reading the project:
07:53:31    ERROR: Runtime Error
  Could not find profile named 'integration_tests'
07:53:31  Encountered an error:
Runtime Error
  Could not run dbt

[dbt listing of models begins here...]
```

From that moment on, automatic listing of models doesn't occur when I save a `.sql` file.

**Comment by bdtoole** [comment]
I'm going through the upgrade right now, and I've noticed the same issue. Do you happen to have the `calogica/dbt_date` package in your environment? I noticed the dbt_project.yml file within that package references an `integration_tests` profile, and I'm wondering if there's some compatibility issue between this extension, the package, and the latest version (perhaps due to the default `dbt_modules` path being changed to `dbt_packages`?

```
name: 'dbt_date'
version: '0.5.0'

config-version: 2

target-path: "target"
clean-targets: ["target", "dbt_packages"]
macro-paths: ["macros"]
log-path: "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]
profile: integration_tests

quoting:
    identifier: false
    schema: false

vars:
    'dbt_date:time_zone': 'America/Los_Angeles'
```
On the plus side, I haven't seen anything issues with the hyperlink navigation, parent/child relationship tree, or the show sql functionality, which are the main reasons I use this extension.

**Comment by ljhopkins2** [comment]
I don't have that package, but at your suggestion, I looked at the `dbt_utils` package—the one package we're using in our project, and it has a profile named `integration_tests`, too.

```
[from dbt_packages/dbt_utils/integration_tests/dbt_project.yml]

name: 'dbt_utils_integration_tests'
version: '1.0'

profile: 'integration_tests'
```
I think you're on to something.

**Comment by mdesmet** [comment]
The rename of dbt_modules in dbt_packages causes this issue I think. Fixed in master, but need to retest pre 1.0 dbt.

**Comment by mdesmet** [comment]
Should be fixed in the just released 0.5.10 release, let me know if it works for you.

**Comment by mdesmet** [comment]
I've updated the visual code publishing plugin and now the publish succeeded.

**Comment by ljhopkins2** [comment]
I've installed 0.5.10, and the issue is resolved. Merci beaucoup!

**Comment by alexchouraki** [comment]
Hello,

I'm having the exact same issue.

Everything runs fine directly within the terminal with dbt debug: 

` Running with dbt=1.0.1
dbt version: 1.0.1
python version: 3.9.7
python path: /opt/conda/bin/python3.9
os info: Linux-5.10.25-linuxkit-x86_64-with-glibc2.31
Using profiles.yml file at /home/<some_path>/.dbt/profiles.yml
Using dbt_project.yml file at /home/<some_path>/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
<some info related to database>
  Connection test: [OK connection ok]`

And I can list my models without issues as well.

But the Tasks - dbt terminal displays the following:

```
> Executing task:  dbt list

16:39:34  Encountered an error while reading the project:
16:39:34    ERROR: Runtime Error
  Could not find profile named '<my_profile_name>'
16:39:34  Encountered an error:
Runtime Error
  Could not run dbt

```

The issue is, I'm using 0.5.10, and this happens with my own dbt profile. I've tried downgrading, just to check, and I'm getting the error twice, once for profile named 'integration_tests', and once for my own. 

I'm kinda at a loss as to what to do here...

**Comment by mdesmet** [comment]
It's not really the same issue (this issue was that we shouldn't look for projects inside dbt_modules or dbt_packages). 

So your profile is in the standard directory ~/.dbt/? We launch dbt list as a child process of vscode, it won't necesarely have the same environment variables set as in your terminal.

**Comment by mdesmet** [comment]
Did you select the correct python interpreter, the one running in the
devcontainer?

**Comment by alexchouraki** [comment]
I think so, yes!
<img width="1010" alt="Screenshot 2022-02-06 at 19 00 40" src="https://user-images.githubusercontent.com/32514048/152694612-cf97d16e-5b63-499a-a08d-094ec5b4971a.png">

**Comment by mdesmet** [comment]
No, it's not the correct one. you need to select the python interpreter running in your dev container:

![image](https://user-images.githubusercontent.com/9265503/152694826-e7f686cd-cf44-49c7-85c7-5719eec44e0a.png)

**Comment by alexchouraki** [comment]
Oh, okay, thank you! 
I'm getting "dbt is not installed" now, but I guess some more configuration should eventually solve this...

**Comment by mdesmet** [comment]
If you select the right environment, it should also detect dbt, as you said
dbt is working in your terminal on the dev container. "dbt is not
installed" means that it could not find dbt in the selected
python environment. there is no configuration except choosing the right
python environment.
